### PR TITLE
MAX IV changes

### PR DESCRIPTION
**Pull request by hormiai76**
- The pom.xml has been modified in order to update some emails, customize the name of the 'ParcelLabelsTemplate' pdf file, add the samplechanger.capacity, update our userportal.url.
- The mainCreatePuck.js has been customized passing the MAXIV site parameter to hide the ESRF info label.
- The 'Take off row for BX/SAXS proposal' changes have been undone in another commit.
- UserPortalRestWebService.java has been modified. The new function gives us the possibility to update the database passing start and end date of the MAXIV proposals' sessions in the ISPyB Client. We will apply for a pull request in the ISPyB CLient project too.
- The UpdateFromSMIS.java has been modified to fit our needs (4h shifts, only get the sessions in the next 14 days, fill the participants table with all the coproposers)
- MAXIVWebService.java has been created to connect to our User Office portal and update the database

### CODE REVIEW

**Comment by delageniere** [comment]
Hi,
When deploying the version merged I have a lot of errors coming from the org.apache.struts.taglib.html.XXX missing
May be some jars are missing or some other maven dependencies ?
Thanks,
Solange

See file:
[missing dependencies.txt](https://github.com/ispyb/ISPyB/files/1830104/missing.dependencies.txt)

-------------------

**Comment by hormiai76** [comment]
Hi Solange
We got this error 1 month ago due to problems with the maven repository in the Jenkins node when I merged the code form the github repo but it worked fine in my local environment so I created the ear file 
 in my laptop and push it on production manually and it worked in our production server. It happened after an update in Jenkins so we assumed something was broken in the jenkins installation,. System guys update java and the repository disappeared.
I will check again our pom.xml files and return to you. 
Alberto

**Comment by hormiai76** [comment]
Hi Solange,
I just checked the pom files and I cannot find anything wrong... the only diferences are some new properties used by MAXIV...
I just realized that I forgot to set 2 properties in the **ispyb-ejb/pom.xml** for all the other facilities: 
- The **dewar.label.templatebecause**. I generalized it and now we can have create our own template for the dewar labels 
- The **samplechanger.capacity**. We have a bigger sample charger and in the prepare your experiment we can select up to 29 locations in the sample changer.

I'm sorry but I realized only now that this problem can affect all the other facilities.

Info about the dependencies problem you got in your environment:
As the development guide suggests we installed manually all the dependencies and then everything worked fine. The Jenkins problems was caused becasue the system guys removed the maven repository folder from the node and the jenkins job couldn't able to create the ear. 
I don't think it's a problem caused by our merge request.
Alberto

**Comment by hormiai76** [comment]
Hi Solange, 
I found the error... the main problem was the new property I added only in the MAX IV profile. I added to all the facility profiles so now it should work fine for you.
Just a question, My jenkins job return to me that it cannot find a missing dependence "tomcat:commons-fileuploader". I checked it and maven moved the artifact to another group and now the latest version is 1.3.3. Is it possible to upload this dependency? The previous versdion is not available anymore.
Alberto

**Comment by delageniere** [comment]
Hi Alberto,
Thanks for the fix, it is ok now.
Yes, we can upload the new dependency for commons-filuploader, may be first check if it is needed.
Solange

**Pull request merged**
